drop table if exists extension;

create table extension (
                        id bigint generated by default as identity,
                        name varchar(255),
                        type varchar(10),
                        checked varchar(10) default 'N',
                        primary key (id)
);